# Generated by Django 4.1 on 2022-08-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealFix', '0002_recept_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recept',
            name='ingridients',
        ),
        migrations.RemoveField(
            model_name='recept',
            name='nutri_info',
        ),
        migrations.AddField(
            model_name='recept',
            name='calories',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='carbs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='fat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='fiber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='protein',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='sugar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
