# Generated by Django 4.1 on 2022-08-30 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealFix', '0007_dish_cuisine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recept',
            options={'ordering': ('title',)},
        ),
    ]
