# Generated by Django 4.1 on 2022-08-30 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealFix', '0008_alter_recept_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recept',
            options={},
        ),
    ]
