# Generated by Django 4.1 on 2022-08-30 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealFix', '0009_alter_recept_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
