# Generated by Django 4.1 on 2022-08-31 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealFix', '0011_recept_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='tod',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
