# Generated by Django 4.1 on 2022-08-31 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealFix', '0012_recept_tod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recept',
            old_name='rating',
            new_name='servings',
        ),
    ]
