# Generated by Django 4.1 on 2022-09-01 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealFix', '0014_remove_recept_steps_recept_step1_recept_step10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='bigsix',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='cuisine',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recept',
            name='dish_style',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
