# Generated by Django 4.1 on 2022-09-03 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealFix', '0015_recept_bigsix_recept_cuisine_recept_dish_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='recept',
            name='myrecipes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
